version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/info.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  file_json:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/application.json
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  # Root logger
  "":
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false

  # Application modules
  backend:
    level: DEBUG
    handlers: [console, file_debug, file_error]
    propagate: false

  backend.core:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: false

  backend.vision:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: false

  backend.api:
    level: INFO
    handlers: [console, file_info, file_json]
    propagate: false

  backend.projector:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: false

  backend.config:
    level: INFO
    handlers: [console, file_info]
    propagate: false

  # Third-party libraries
  uvicorn:
    level: INFO
    handlers: [console, file_info]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [file_info]
    propagate: false

  fastapi:
    level: INFO
    handlers: [console, file_info]
    propagate: false

  websockets:
    level: WARNING
    handlers: [console, file_error]
    propagate: false

  opencv:
    level: WARNING
    handlers: [file_error]
    propagate: false

# Development environment overrides
development:
  loggers:
    "":
      level: DEBUG
      handlers: [console, file_debug, file_error]
    backend:
      level: DEBUG
    backend.vision:
      level: DEBUG
    backend.core:
      level: DEBUG

# Production environment overrides
production:
  formatters:
    default:
      format: "%(asctime)s - %(levelname)s - %(message)s"

  loggers:
    "":
      level: INFO
      handlers: [file_info, file_error, file_json]
    backend:
      level: INFO
      handlers: [file_info, file_error]
    uvicorn.access:
      level: WARNING

# Testing environment overrides
testing:
  handlers:
    console:
      level: WARNING

  loggers:
    "":
      level: WARNING
      handlers: [console]
    backend:
      level: WARNING
      handlers: [console]
